#### Plugin Versions ####
[plugins]
android-application = { id = "com.android.application", version = "8.7.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.10" }

#### Library Versions ####
[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.10.1" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.1" }
material = { group = "com.google.android.material", name = "material", version = "1.9.0" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version = "1.7.2" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }

#### Test Library Versions ####
junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.1.5" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.5.1" }

#### Version References ####
[versions]
compileSdk = "34"
minSdk = "24"
targetSdk = "34"
kotlin-jvm = "1.8"

